# <center> Лабораторна робота №1
### Виконав:
### Студент групи ПБ-21мп
### Гриценко Ярослав

# Початок роботи з бібліотекою Numpy

У даній лабораторній роботі розглянуто наступний функціонал бібліотеки Numpy:
1. Створення масиву.
2. Відображення масивів .
3. Базові операції з масивами.

## Імпорт бібліотек та пакетів

Завантажуємо бібліотеку numpy та використаємо скорочення np.

In [21]:
import numpy as np

# Завдання
## 1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [22]:
size = (11,11)

1.2. Створити нульовий масив заданого розміру

In [23]:
array = np.zeros(size)

1.3 Надрукувати створений масив

In [24]:
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінити діагоналі за допомогою двох циклів

In [25]:
for i in range(size[0]):
	for j in range(size[1]):
		if (i == j):
			array[i][j] = 1
		elif (i + j == size[0] - 1):
			array[i][j] = 1

1.5 Вивести створений масив

In [5]:
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).

### Горизонтальний градієнт

2.1 Створити нульовий масив розміром 255х255

In [26]:
horizontal_gradient1 = np.zeros([255,255])

2.2 Визначити розміри масиву

In [27]:
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

2.3 Поелементно змінити яскравості кожного пікселя

In [29]:
n = 0
for i in range(w):
    for j in range(h):
        horizontal_gradient1[j][i] = n
    n += 1
    
print(horizontal_gradient1)

[[  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]
 ...
 [  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]
 [  0.   1.   2. ... 252. 253. 254.]]


2.4 Записати зображення засабами OpenCV

In [30]:
import cv2
cv2.imwrite('horizontal_grad1.jpg', horizontal_gradient1)

True

2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [40]:
horizontal_gradient2 = np.zeros([255,255])

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]

n = h - 1
for i in range(w):
    for j in range(h):
        horizontal_gradient2[j][i] = n
    n -= 1
    
print(horizontal_gradient2)

cv2.imwrite('horizontal_grad2.jpg', horizontal_gradient2)

[[254. 253. 252. ...   2.   1.   0.]
 [254. 253. 252. ...   2.   1.   0.]
 [254. 253. 252. ...   2.   1.   0.]
 ...
 [254. 253. 252. ...   2.   1.   0.]
 [254. 253. 252. ...   2.   1.   0.]
 [254. 253. 252. ...   2.   1.   0.]]


True

### Вертикальний градієнт

2.6 Створити нульовий масив розміром 255х255

In [41]:
vertical_gradient1 = np.zeros([255,255])

2.7 Визначити розміри масиву

In [42]:
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]

2.8 Поелементно змінити яскравості кожного пікселя

In [43]:
m = 0
for i in range(w):
    for j in range(h):
        vertical_gradient1[i][j] = m
    m += 1
    
print(vertical_gradient1)

[[  0.   0.   0. ...   0.   0.   0.]
 [  1.   1.   1. ...   1.   1.   1.]
 [  2.   2.   2. ...   2.   2.   2.]
 ...
 [252. 252. 252. ... 252. 252. 252.]
 [253. 253. 253. ... 253. 253. 253.]
 [254. 254. 254. ... 254. 254. 254.]]


2.9 Записати зображення засабами OpenCV

In [36]:
cv2.imwrite('vertical_grad1.jpg', vertical_gradient1)

True

2.10 Аналогічно створити горизонтальний градієнт в інший бік

In [44]:
vertical_gradient2 = np.zeros([255,255])

w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]

m = h - 1
for i in range(w):
    for j in range(h):
        vertical_gradient2[i][j] = m
    m -= 1
    
print(vertical_gradient2)
        
cv2.imwrite('vertical_grad2.jpg', vertical_gradient2)

[[254. 254. 254. ... 254. 254. 254.]
 [253. 253. 253. ... 253. 253. 253.]
 [252. 252. 252. ... 252. 252. 252.]
 ...
 [  2.   2.   2. ...   2.   2.   2.]
 [  1.   1.   1. ...   1.   1.   1.]
 [  0.   0.   0. ...   0.   0.   0.]]


True